# Generated by Django 5.2.11 on 2026-03-28 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSearchTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional label for this task', max_length=255)),
                ('search_term', models.CharField(max_length=512)),
                ('location', models.CharField(blank=True, max_length=512)),
                ('track', models.CharField(default='ic', help_text="Track slug this task feeds, e.g. 'ic', 'mgmt', or a custom track.", max_length=32)),
                ('jobs_to_fetch', models.PositiveIntegerField(default=50)),
                ('site_name', models.JSONField(default=list, help_text="e.g. ['indeed']")),
                ('frequency', models.CharField(help_text="Cron expression, e.g. '0 9 * * *' for daily 9am. Validated on save.", max_length=128)),
                ('start_time', models.TimeField(blank=True, help_text="Time of day for first run and staggering so tasks don't overlap.", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LLMAppUsageTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_input_tokens', models.BigIntegerField(default=0)),
                ('total_output_tokens', models.BigIntegerField(default=0)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('total_estimated_invokes', models.PositiveIntegerField(default=0, help_text='Calls where tokens were heuristic (provider did not report usage).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM app usage totals',
                'verbose_name_plural': 'LLM app usage totals',
            },
        ),
        migrations.CreateModel(
            name='LLMProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64, unique=True)),
                ('encrypted_api_key', models.TextField(blank=True)),
                ('default_model', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=False, help_text='DB-backed active provider for background jobs (Huey) and web flows.')),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Lower number = higher preference when active provider is unavailable.')),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Provider Config',
                'verbose_name_plural': 'LLM Provider Configs',
            },
        ),
        migrations.CreateModel(
            name='OptimizerWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('steps', models.JSONField(help_text="Ordered list of step ids, e.g. ['writer', 'ats_judge', 'recruiter_judge']")),
                ('loop_to', models.CharField(blank=True, max_length=64)),
                ('max_iterations', models.PositiveSmallIntegerField(default=3)),
                ('score_threshold', models.PositiveSmallIntegerField(default=85)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Short code used in URLs and tasks, e.g. 'ic', 'mgmt', 'eu_ic'.", max_length=32, unique=True)),
                ('label', models.CharField(help_text="Human-friendly name, e.g. 'IC (Principal / Staff)'.", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='If true, used as fallback when no track is selected.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='UserDisqualifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['phrase'],
            },
        ),
        migrations.CreateModel(
            name='UserPromptProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.TextField(blank=True)),
                ('writer_system', models.TextField(blank=True)),
                ('writer_user', models.TextField(blank=True)),
                ('ats_judge', models.TextField(blank=True)),
                ('ats_judge_system', models.TextField(blank=True)),
                ('ats_judge_user', models.TextField(blank=True)),
                ('recruiter_judge', models.TextField(blank=True)),
                ('recruiter_judge_system', models.TextField(blank=True)),
                ('recruiter_judge_user', models.TextField(blank=True)),
                ('matching', models.TextField(blank=True)),
                ('matching_system', models.TextField(blank=True)),
                ('matching_user', models.TextField(blank=True)),
                ('insights', models.TextField(blank=True)),
                ('insights_system', models.TextField(blank=True)),
                ('insights_user', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User prompt profile',
                'verbose_name_plural': 'User prompt profiles',
            },
        ),
        migrations.AddField(
            model_name='optimizedresume',
            name='ats_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optimizedresume',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optimizedresume',
            name='recruiter_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optimizedresume',
            name='status_display',
            field=models.CharField(blank=True, help_text="Human-readable progress, e.g. 'Drafting iteration 1'", max_length=255),
        ),
        migrations.AddField(
            model_name='optimizedresume',
            name='total_input_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optimizedresume',
            name='total_output_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original name of the uploaded file', max_length=255),
        ),
        migrations.AddField(
            model_name='userresume',
            name='track',
            field=models.CharField(blank=True, default='', help_text='Preferred preference track slug for this resume (used to default Job Search track).', max_length=32),
        ),
        migrations.AlterField(
            model_name='optimizedresume',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=255),
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64)),
                ('external_id', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=512)),
                ('company_name', models.CharField(max_length=512)),
                ('location', models.CharField(blank=True, max_length=512)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('pipeline_last_scored_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'unique_together': {('source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='JobSearchTaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16)),
                ('jobs_fetched', models.PositiveIntegerField(default=0)),
                ('jobs_after_filter', models.PositiveIntegerField(default=0)),
                ('jobs_added_to_pipeline', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='resume_app.jobsearchtask')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMProviderPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=128)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('rate_limit_rpm', models.PositiveIntegerField(blank=True, help_text='Optional max requests per minute for this provider+model row. Empty = use env/provider defaults or no limit.', null=True)),
                ('rate_limit_tpm', models.PositiveIntegerField(blank=True, help_text='Optional max input tokens per minute (estimated) for this row. Empty = use env/provider defaults or no limit.', null=True)),
                ('rate_limit_cooldown_seconds', models.PositiveIntegerField(blank=True, help_text='After rate limit or 429, skip this provider+model for this many seconds (empty = 300).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_rows', to='resume_app.llmproviderconfig')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LLMUsageByModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=64)),
                ('model', models.CharField(db_index=True, help_text='Resolved model name, or __default__ when empty.', max_length=128)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('sum_input_tokens', models.BigIntegerField(default=0)),
                ('sum_output_tokens', models.BigIntegerField(default=0)),
                ('sum_cached_tokens', models.BigIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'LLM usage by model',
                'verbose_name_plural': 'LLM usage by model',
                'unique_together': {('provider', 'model')},
            },
        ),
        migrations.CreateModel(
            name='LLMUsageByQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_kind', models.CharField(db_index=True, max_length=64)),
                ('provider', models.CharField(db_index=True, max_length=64)),
                ('model', models.CharField(db_index=True, help_text='Resolved model name, or __default__ when empty.', max_length=128)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('sum_input_tokens', models.BigIntegerField(default=0)),
                ('sum_output_tokens', models.BigIntegerField(default=0)),
                ('sum_cached_tokens', models.BigIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'LLM usage by query',
                'verbose_name_plural': 'LLM usage by query',
                'unique_together': {('query_kind', 'provider', 'model')},
            },
        ),
        migrations.CreateModel(
            name='AppAutomationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_to_vetting_enabled', models.BooleanField(default=False)),
                ('pipeline_preference_margin_min', models.IntegerField(default=0, help_text='Promote Pipeline → Vetting when Pref margin (same as pipeline badge) is >= this value.')),
                ('vetting_to_applying_enabled', models.BooleanField(default=False)),
                ('vetting_interview_probability_min', models.PositiveSmallIntegerField(default=70, help_text='Promote Vetting → Applying when interview probability is >= this (0–100).')),
                ('stop_llm_requests', models.BooleanField(default=False, help_text='When set, the app will not send any LLM API requests (kill switch).')),
                ('cleanup_pipeline_retention_days', models.PositiveSmallIntegerField(default=2, help_text='Cleanup Manager: remove Pipeline-stage rows older than this many days (0 = off).')),
                ('cleanup_vetting_retention_days', models.PositiveSmallIntegerField(default=6, help_text='Cleanup Manager: remove Vetting-stage rows older than this many days (0 = off).')),
                ('cleanup_applying_retention_days', models.PositiveSmallIntegerField(default=10, help_text='Cleanup Manager: remove Applying-stage rows older than this many days (0 = off).')),
                ('cleanup_done_retention_days', models.PositiveSmallIntegerField(default=0, help_text='Cleanup Manager: remove Done-stage rows older than this many days (0 = off).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applying_optimizer_workflow', models.ForeignKey(blank=True, help_text='Default Resume Optimizer workflow for Applying-stage runs (auto + bulk).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='resume_app.optimizerworkflow')),
            ],
            options={
                'verbose_name': 'App automation settings',
                'verbose_name_plural': 'App automation settings',
            },
        ),
        migrations.AddField(
            model_name='optimizedresume',
            name='optimizer_workflow',
            field=models.ForeignKey(blank=True, help_text='Saved workflow used when this run was enqueued.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimized_resumes', to='resume_app.optimizerworkflow'),
        ),
        migrations.CreateModel(
            name='PipelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(help_text='Track slug for this pipeline row.', max_length=32)),
                ('stage', models.CharField(blank=True, choices=[('pipeline', 'Pipeline'), ('vetting', 'Vetting'), ('applying', 'Applying'), ('done', 'Done'), ('deleted', 'Deleted')], default='', help_text='Lightweight stage for this job in the pipeline (e.g. vetting, applying, done). Blank means legacy/default pipeline.', max_length=16)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('vetting_interview_probability', models.IntegerField(blank=True, null=True)),
                ('vetting_interview_reasoning', models.TextField(blank=True, null=True)),
                ('vetting_interview_resume_id', models.IntegerField(blank=True, null=True)),
                ('vetting_interview_scored_at', models.DateTimeField(blank=True, null=True)),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_app.joblisting')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('job_listing', 'track')},
            },
        ),
        migrations.AddField(
            model_name='optimizedresume',
            name='pipeline_entry',
            field=models.ForeignKey(blank=True, help_text='Pipeline row this optimization was started for (Applying stage).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimized_resumes', to='resume_app.pipelineentry'),
        ),
        migrations.CreateModel(
            name='JobListingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('liked', 'Liked'), ('disliked', 'Disliked'), ('saved', 'Saved')], max_length=16)),
                ('track', models.CharField(blank=True, default='', help_text="Preference track slug for likes/dislikes/saves (e.g. 'ic', 'mgmt'). Empty for legacy/global rows.", max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_app.joblisting')),
            ],
            options={
                'unique_together': {('job_listing', 'action', 'track')},
            },
        ),
        migrations.CreateModel(
            name='JobListingEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_type', models.CharField(choices=[('liked', 'Liked'), ('disliked', 'Disliked')], default='liked', max_length=16)),
                ('track', models.CharField(blank=True, default='', help_text="Preference track: 'ic' or 'mgmt' for likes/dislikes; empty for legacy/global.", max_length=16)),
                ('embedding', models.JSONField(help_text='List of floats, e.g. 384-dim from sentence-transformers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_app.joblisting')),
            ],
            options={
                'unique_together': {('job_listing', 'embedding_type', 'track')},
            },
        ),
        migrations.CreateModel(
            name='JobListingTrackMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(help_text="Track slug, e.g. 'ic', 'mgmt', or a custom track.", max_length=32)),
                ('focus_percent', models.IntegerField(blank=True, null=True)),
                ('focus_after_penalty', models.IntegerField(blank=True, null=True)),
                ('preference_margin', models.IntegerField(blank=True, null=True)),
                ('last_scored_at', models.DateTimeField(blank=True, null=True)),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_app.joblisting')),
            ],
            options={
                'indexes': [models.Index(fields=['track', 'job_listing'], name='resume_app__track_90ff7c_idx')],
                'unique_together': {('job_listing', 'track')},
            },
        ),
        migrations.CreateModel(
            name='JobMatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_score', models.IntegerField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('analyzed', 'Analyzed'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], default='analyzed', max_length=32)),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_app.joblisting')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_app.userresume')),
            ],
            options={
                'ordering': ['-analyzed_at'],
                'unique_together': {('job_listing', 'resume')},
            },
        ),
    ]
