# Generated by Django 5.2.11 on 2026-05-09 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "resume_app",
            "0002_jobsearchtask_llmappusagetotals_llmproviderconfig_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="optimizedresume",
            name="job_highlights",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional short job-specific bullets (token-capped).",
            ),
        ),
        migrations.AddField(
            model_name="optimizedresume",
            name="optimization_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional user notes passed to the Writer (token-capped).",
            ),
        ),
        migrations.AddField(
            model_name="optimizedresume",
            name="optimizer_context_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="Last run: writer JD/resume budgets, retrieval stats (debug).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="optimizedresume",
            name="pipeline_skills_json",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional JSON or keyword blob from pipeline (token-capped).",
            ),
        ),
        migrations.CreateModel(
            name="ResumeChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordinal", models.PositiveIntegerField()),
                ("section", models.CharField(blank=True, default="", max_length=64)),
                ("text", models.TextField()),
                (
                    "embedding",
                    models.JSONField(
                        help_text="384-dim float list (sentence-transformers)"
                    ),
                ),
                ("embedding_model", models.CharField(max_length=128)),
                ("source_fingerprint", models.CharField(db_index=True, max_length=64)),
                (
                    "user_resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_chunks",
                        to="resume_app.userresume",
                    ),
                ),
            ],
            options={
                "ordering": ["user_resume_id", "ordinal"],
                "indexes": [
                    models.Index(
                        fields=["user_resume", "source_fingerprint"],
                        name="resume_app__user_re_7ae4d2_idx",
                    )
                ],
            },
        ),
    ]
