# Generated by Django 5.2.11 on 2026-05-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0003_optimizedresume_job_highlights_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmproviderpreference",
            name="is_local",
            field=models.BooleanField(
                default=False,
                help_text="If true, this provider+model is treated as local (prioritized or required).",
            ),
        ),
    ]
