# Generated by Django 5.2.11 on 2026-06-02 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0008_joblisting_posted_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userresume',
            new_name='resume_app__is_libr_d504ff_idx',
            old_name='resume_app__is_lib_8a1f0d_idx',
        ),
    ]
