# Generated by Django 5.2.11 on 2026-06-09 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0009_rename_resume_app__is_lib_8a1f0d_idx_resume_app__is_libr_d504ff_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('linkedin_url', models.URLField(blank=True, default='', max_length=512)),
                ('website_url', models.URLField(blank=True, default='', max_length=512)),
                ('work_authorization', models.CharField(blank=True, default='', help_text="e.g. 'US Citizen', 'Green Card', 'H-1B'. Used for work-eligibility questions.", max_length=255)),
                ('requires_sponsorship', models.BooleanField(default=False, help_text="Answer to 'Do you require sponsorship?' style questions.")),
                ('salary_expectation', models.CharField(blank=True, default='', max_length=128)),
                ('cover_letter_template', models.TextField(blank=True, default='', help_text='Optional default cover letter / message body. Placeholders like {company} and {title} are substituted.')),
                ('custom_qa_pairs', models.JSONField(blank=True, default=dict, help_text="Key/value answers for edge-case questions (e.g. {'GitHub URL': '...', 'Years with Django': '5'}).")),
                ('include_eeo', models.BooleanField(default=False, help_text='If false, the agent leaves voluntary EEO/demographic questions blank.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Applicant profile',
                'verbose_name_plural': 'Applicant profile',
            },
        ),
        migrations.CreateModel(
            name='AtsAutoSubmitStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_type', models.CharField(max_length=32, unique=True)),
                ('clean_submit_streak', models.PositiveIntegerField(default=0, help_text='Consecutive approved submissions with no human corrections. Resets to 0 on any correction.')),
                ('total_submits', models.PositiveIntegerField(default=0)),
                ('total_corrections', models.PositiveIntegerField(default=0)),
                ('full_auto_enabled', models.BooleanField(default=False, help_text='When true (and global mode allows), this ATS may submit without review.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ATS auto-submit stats',
                'verbose_name_plural': 'ATS auto-submit stats',
            },
        ),
        migrations.CreateModel(
            name='SiteCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text="Host the credential applies to, e.g. 'boards.greenhouse.io' or 'acme.com'.", max_length=255, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('encrypted_password', models.TextField(blank=True, default='')),
                ('encrypted_session_cookies', models.TextField(blank=True, default='', help_text='Encrypted JSON blob of cookies for explicit injection into a fresh browser context.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
        migrations.AddField(
            model_name='appautomationsettings',
            name='apply_agent_enabled',
            field=models.BooleanField(default=False, help_text='Master switch for the Autonomous Apply Agent (browser automation).'),
        ),
        migrations.AddField(
            model_name='appautomationsettings',
            name='apply_allowed_ats',
            field=models.JSONField(blank=True, default=list, help_text="ATS slugs the agent is allowed to apply to (e.g. ['greenhouse', 'lever']). Empty = greenhouse + lever defaults."),
        ),
        migrations.AddField(
            model_name='appautomationsettings',
            name='apply_automation_mode',
            field=models.CharField(choices=[('semi_auto', 'Semi-auto (review before submit)'), ('full_auto', 'Full-auto (submit without review)')], default='semi_auto', help_text='Semi-auto pauses for human approval before submitting; full-auto submits autonomously for graduated ATS adapters only.', max_length=16),
        ),
        migrations.AddField(
            model_name='appautomationsettings',
            name='apply_full_auto_min_clean_submits',
            field=models.PositiveSmallIntegerField(default=10, help_text='An ATS may graduate to full-auto only after this many approved submissions with zero human corrections.'),
        ),
        migrations.AddField(
            model_name='appautomationsettings',
            name='apply_generic_fallback_enabled',
            field=models.BooleanField(default=True, help_text='Use the browser-use generic agent for unknown ATS (always requires review; never auto-submits).'),
        ),
        migrations.AddField(
            model_name='appautomationsettings',
            name='apply_min_optimizer_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Require optimized resume avg (ATS+recruiter) >= this before applying (0 = no gate).'),
        ),
        migrations.AddField(
            model_name='appautomationsettings',
            name='apply_resume_upload_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word (DOCX)')], default='pdf', help_text='File format used when the agent uploads the optimized resume. PDF is the stable default for v1.', max_length=8),
        ),
        migrations.CreateModel(
            name='ApplicationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('optimizing', 'Optimizing resume'), ('waiting_optimizer', 'Waiting for optimizer'), ('resolve_and_detect', 'Resolving URL'), ('dry_run_fill', 'Dry-run fill'), ('awaiting_approval', 'Awaiting approval'), ('submitting', 'Submitting'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=24)),
                ('automation_mode', models.CharField(choices=[('semi_auto', 'Semi-auto'), ('full_auto', 'Full-auto')], default='semi_auto', max_length=16)),
                ('apply_url', models.URLField(blank=True, default='', max_length=2048)),
                ('ats_type', models.CharField(blank=True, default='', help_text='Detected ATS slug, e.g. greenhouse, lever, workday, unknown.', max_length=32)),
                ('confidence', models.FloatField(blank=True, help_text='Adapter/agent confidence (0.0–1.0) that the form was filled correctly.', null=True)),
                ('fill_payload_json', models.JSONField(blank=True, help_text='Semantic answer key captured in the dry run (field label -> value). Never stores CSRF/hidden tokens.', null=True)),
                ('session_state_json', models.JSONField(blank=True, help_text='Optional login cookies/storage for explicit injection into a fresh context (not form anti-fraud tokens).', null=True)),
                ('resume_file_path', models.CharField(blank=True, default='', help_text='Path to the exported optimized resume (PDF/DOCX) used for upload.', max_length=1024)),
                ('error_code', models.CharField(blank=True, default='', max_length=32)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, help_text='Set when a worker begins processing a step; used to detect stuck attempts.', null=True)),
                ('optimized_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_attempts', to='resume_app.optimizedresume')),
                ('pipeline_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_attempts', to='resume_app.pipelineentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAttemptStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=64)),
                ('message', models.TextField(blank=True, default='')),
                ('screenshot_path', models.CharField(blank=True, default='', max_length=1024)),
                ('action_snapshot', models.JSONField(blank=True, help_text='Structured snapshot of actions taken / fields filled in this step.', null=True)),
                ('network_log', models.JSONField(blank=True, default=list, help_text='XHR/fetch responses observed during this step (catches silent ATS validation errors).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='resume_app.applicationattempt')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='applicationattempt',
            index=models.Index(fields=['status', '-created_at'], name='resume_app__status_236f76_idx'),
        ),
    ]
