# Generated by Django for retaining uploaded resume filename

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0011_remove_dealbreakers"),
    ]

    operations = [
        migrations.AddField(
            model_name="userresume",
            name="original_filename",
            field=models.CharField(blank=True, help_text="Original name of the uploaded file", max_length=255),
        ),
    ]
