# Generated by Django for disliked job listing embeddings (listing-level, for similarity penalty)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0012_userresume_original_filename"),
    ]

    operations = [
        migrations.CreateModel(
            name="DislikedJobListingEmbedding",
            fields=[
                ("job_listing", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to="resume_app.joblisting")),
                ("embedding", models.JSONField(help_text="List of floats, listing-level embedding")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
