# Generated by Django 5.2.11 on 2026-03-11 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0014_optimizer_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislikedjoblistingembedding',
            name='job_listing',
        ),
        migrations.RemoveField(
            model_name='likedjoblisting',
            name='job_listing',
        ),
        migrations.RemoveField(
            model_name='savedjoblisting',
            name='job_listing',
        ),
        migrations.RemoveField(
            model_name='jobmatchresult',
            name='thoughts',
        ),
        migrations.AddField(
            model_name='joblistingembedding',
            name='embedding_type',
            field=models.CharField(choices=[('liked', 'Liked'), ('disliked', 'Disliked')], default='liked', max_length=16),
        ),
        migrations.AddField(
            model_name='joblistingembedding',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='joblistingembedding',
            name='job_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_app.joblisting'),
        ),
        migrations.AlterField(
            model_name='optimizedresume',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='joblistingembedding',
            unique_together={('job_listing', 'embedding_type')},
        ),
        migrations.CreateModel(
            name='JobListingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('liked', 'Liked'), ('disliked', 'Disliked'), ('saved', 'Saved')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_app.joblisting')),
            ],
            options={
                'unique_together': {('job_listing', 'action')},
            },
        ),
        migrations.DeleteModel(
            name='DislikedJobListing',
        ),
        migrations.DeleteModel(
            name='DislikedJobListingEmbedding',
        ),
        migrations.DeleteModel(
            name='LikedJobListing',
        ),
        migrations.DeleteModel(
            name='SavedJobListing',
        ),
    ]
