# Generated by Django 5.2.11 on 2026-06-29 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0016_enforce_owner_non_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='atsjudgeprofile',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Null for global built-in seed profiles copied on signup.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ats_judge_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
