# Generated by Django 5.2.11 on 2026-03-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0016_remove_dislikedjoblistingembedding_job_listing_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joblistingembedding',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='joblistingaction',
            name='track',
            field=models.CharField(blank=True, default='', help_text="Preference track: 'ic' or 'mgmt' for likes/dislikes; empty for legacy/global.", max_length=16),
        ),
        migrations.AddField(
            model_name='joblistingembedding',
            name='track',
            field=models.CharField(blank=True, default='', help_text="Preference track: 'ic' or 'mgmt' for likes/dislikes; empty for legacy/global.", max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='joblistingembedding',
            unique_together={('job_listing', 'embedding_type', 'track')},
        ),
    ]
