# Generated by Django 5.2.11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0017_alter_joblistingembedding_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSearchTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional label for this task', max_length=255)),
                ('search_term', models.CharField(max_length=512)),
                ('location', models.CharField(blank=True, max_length=512)),
                ('track', models.CharField(default='ic', max_length=16)),
                ('jobs_to_fetch', models.PositiveIntegerField(default=50)),
                ('site_name', models.JSONField(default=list, help_text="e.g. ['indeed']")),
                ('frequency', models.CharField(help_text="Cron expression, e.g. '0 9 * * *' for daily 9am. Validated on save.", max_length=128)),
                ('start_time', models.TimeField(blank=True, help_text="Time of day for first run and staggering so tasks don't overlap.", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobSearchTaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16)),
                ('jobs_fetched', models.PositiveIntegerField(default=0)),
                ('jobs_after_filter', models.PositiveIntegerField(default=0)),
                ('jobs_added_to_pipeline', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='resume_app.jobsearchtask')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=16)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_app.joblisting')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('job_listing', 'track')},
            },
        ),
    ]
