# Generated by Django 5.2.11 on 2026-03-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0018_job_search_task_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='pipeline_focus_after_penalty_ic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='pipeline_focus_after_penalty_mgmt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='pipeline_focus_percent_ic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='pipeline_focus_percent_mgmt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='pipeline_last_scored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='pipeline_preference_margin_ic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='pipeline_preference_margin_mgmt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
