# Generated by Django 5.2.11 on 2026-07-01 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def _unique_slug(used: set[str], base: str) -> str:
    root = (slugify(base) or "search")[:28]
    slug = root
    n = 2
    while slug in used:
        suffix = f"-{n}"
        slug = f"{root[: 32 - len(suffix)]}{suffix}"
        n += 1
    used.add(slug)
    return slug


def backfill_slugs(apps, schema_editor):
    SearchProfile = apps.get_model("resume_app", "SearchProfile")
    for owner_id in SearchProfile.objects.values_list("owner_id", flat=True).distinct():
        used: set[str] = set()
        for sp in SearchProfile.objects.filter(owner_id=owner_id).order_by("id"):
            raw = (sp.profile_slug or "").strip().lower()
            if not raw:
                raw = _unique_slug(used, sp.name)
            elif raw in used:
                raw = _unique_slug(used, sp.name)
            else:
                used.add(raw)
            sp.slug = raw
            sp.profile_slug = raw
            if not (sp.search_term or "").strip():
                sp.search_term = (sp.name or raw)[:512]
            sp.save(update_fields=["slug", "profile_slug", "search_term"])


def backfill_profile_fks(apps, schema_editor):
    SearchProfile = apps.get_model("resume_app", "SearchProfile")
    PipelineEntry = apps.get_model("resume_app", "PipelineEntry")
    JobListingAction = apps.get_model("resume_app", "JobListingAction")
    JobListingEmbedding = apps.get_model("resume_app", "JobListingEmbedding")
    JobListingTrackMetrics = apps.get_model("resume_app", "JobListingTrackMetrics")

    for owner_id in SearchProfile.objects.values_list("owner_id", flat=True).distinct():
        by_slug = {
            p.slug: p.id
            for p in SearchProfile.objects.filter(owner_id=owner_id).only("id", "slug")
        }
        for pe in PipelineEntry.objects.filter(owner_id=owner_id, search_profile__isnull=True):
            sp_id = by_slug.get((pe.track or "").strip().lower())
            if sp_id:
                pe.search_profile_id = sp_id
                pe.save(update_fields=["search_profile_id"])
        for model in (JobListingAction, JobListingEmbedding, JobListingTrackMetrics):
            for row in model.objects.filter(owner_id=owner_id, search_profile__isnull=True):
                sp_id = by_slug.get((row.track or "").strip().lower())
                if sp_id:
                    row.search_profile_id = sp_id
                    row.save(update_fields=["search_profile_id"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0019_jobsearchtask_saved_search"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SavedJobSearch",
            new_name="SearchProfile",
        ),
        migrations.AlterModelOptions(
            name="searchprofile",
            options={
                "ordering": ["-updated_at", "name"],
                "verbose_name": "Search profile",
                "verbose_name_plural": "Search profiles",
            },
        ),
        migrations.AlterField(
            model_name="searchprofile",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="searchprofile",
            name="resume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="search_profiles",
                to="resume_app.userresume",
            ),
        ),
        migrations.AlterField(
            model_name="searchprofile",
            name="profile_slug",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Deprecated: legacy track slug mirror; kept in sync with slug during migration.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="searchprofile",
            name="slug",
            field=models.SlugField(
                help_text="URL-safe profile key (unique per owner).",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="searchprofile",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="searchprofile",
            name="schedule_interval",
            field=models.CharField(
                choices=[
                    ("off", "Off"),
                    ("daily", "Daily"),
                    ("weekdays", "Weekdays"),
                    ("weekly", "Weekly"),
                    ("custom", "Custom"),
                ],
                default="off",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="searchprofile",
            name="schedule_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="searchprofile",
            name="schedule_cron",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="searchprofile",
            name="schedule_is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="searchprofile",
            name="schedule_next_run_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="searchprofile",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="At most one default profile per owner (legacy General bucket).",
            ),
        ),
        migrations.RunPython(backfill_slugs, noop_reverse),
        migrations.AlterField(
            model_name="searchprofile",
            name="slug",
            field=models.SlugField(
                help_text="URL-safe profile key (unique per owner).",
                max_length=32,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="searchprofile",
            unique_together={("owner", "name"), ("owner", "slug")},
        ),
        migrations.AlterField(
            model_name="searchprofile",
            name="search_term",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="joblistingaction",
            name="track",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Legacy track slug mirror; kept in sync with search_profile.slug.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="joblistingembedding",
            name="track",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Legacy track slug mirror; kept in sync with search_profile.slug.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="joblistingtrackmetrics",
            name="track",
            field=models.CharField(
                help_text="Legacy track slug mirror; kept in sync with search_profile.slug.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="pipelineentry",
            name="track",
            field=models.CharField(
                help_text="Track slug for this pipeline row (legacy; mirrors search_profile.slug).",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="joblistingaction",
            name="search_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_listing_actions",
                to="resume_app.searchprofile",
            ),
        ),
        migrations.AddField(
            model_name="joblistingembedding",
            name="search_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_embeddings",
                to="resume_app.searchprofile",
            ),
        ),
        migrations.AddField(
            model_name="joblistingtrackmetrics",
            name="search_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_metrics",
                to="resume_app.searchprofile",
            ),
        ),
        migrations.AddField(
            model_name="pipelineentry",
            name="search_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Search profile scope (Phase 1 dual-write with track slug).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pipeline_entries",
                to="resume_app.searchprofile",
            ),
        ),
        migrations.AlterField(
            model_name="jobsearchtask",
            name="saved_search",
            field=models.OneToOneField(
                blank=True,
                help_text="When set, this task runs the linked search profile configuration.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_task",
                to="resume_app.searchprofile",
            ),
        ),
        migrations.RunPython(backfill_profile_fks, noop_reverse),
    ]
