# Generated by Django 5.2.11 on 2026-03-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0019_joblisting_pipeline_focus_after_penalty_ic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Short code used in URLs and tasks, e.g. 'ic', 'mgmt', 'eu_ic'.", max_length=32, unique=True)),
                ('label', models.CharField(help_text="Human-friendly name, e.g. 'IC (Principal / Staff)'.", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='If true, used as fallback when no track is selected.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='joblistingaction',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='joblistingaction',
            name='track',
            field=models.CharField(blank=True, default='', help_text="Preference track slug for likes/dislikes/saves (e.g. 'ic', 'mgmt'). Empty for legacy/global rows.", max_length=32),
        ),
        migrations.AlterField(
            model_name='jobsearchtask',
            name='track',
            field=models.CharField(default='ic', help_text="Track slug this task feeds, e.g. 'ic', 'mgmt', or a custom track.", max_length=32),
        ),
        migrations.AlterField(
            model_name='pipelineentry',
            name='track',
            field=models.CharField(help_text='Track slug for this pipeline row.', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='joblistingaction',
            unique_together={('job_listing', 'action', 'track')},
        ),
    ]
