# Generated by Django 5.2.11 on 2026-03-16 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0020_track_alter_joblistingaction_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListingTrackMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(help_text="Track slug, e.g. 'ic', 'mgmt', or a custom track.", max_length=32)),
                ('focus_percent', models.IntegerField(blank=True, null=True)),
                ('focus_after_penalty', models.IntegerField(blank=True, null=True)),
                ('preference_margin', models.IntegerField(blank=True, null=True)),
                ('last_scored_at', models.DateTimeField(blank=True, null=True)),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_app.joblisting')),
            ],
            options={
                'indexes': [models.Index(fields=['track', 'job_listing'], name='resume_app__track_90ff7c_idx')],
                'unique_together': {('job_listing', 'track')},
            },
        ),
    ]
