# Generated by Django 5.2.11 on 2026-07-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0023_saas_plans_quotas_api_keys'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usagecounter',
            new_name='resume_app__owner_i_389258_idx',
            old_name='resume_app__owner_i_7c1a0d_idx',
        ),
    ]
