# Generated by Django 5.2.11 on 2026-03-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0024_userresume_track_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineentry',
            name='vetting_interview_probability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelineentry',
            name='vetting_interview_reasoning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelineentry',
            name='vetting_interview_resume_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelineentry',
            name='vetting_interview_scored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
