# Generated by Django 5.2.11 on 2026-07-18 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0025_user_email_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPromptProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.TextField(blank=True)),
                ('writer_system', models.TextField(blank=True)),
                ('writer_user', models.TextField(blank=True)),
                ('ats_judge', models.TextField(blank=True)),
                ('ats_judge_system', models.TextField(blank=True)),
                ('ats_judge_user', models.TextField(blank=True)),
                ('recruiter_judge', models.TextField(blank=True)),
                ('recruiter_judge_system', models.TextField(blank=True)),
                ('recruiter_judge_user', models.TextField(blank=True)),
                ('matching', models.TextField(blank=True)),
                ('matching_system', models.TextField(blank=True)),
                ('matching_user', models.TextField(blank=True)),
                ('insights', models.TextField(blank=True)),
                ('insights_system', models.TextField(blank=True)),
                ('insights_user', models.TextField(blank=True)),
                ('jd_cleanse', models.TextField(blank=True)),
                ('jd_cleanse_system', models.TextField(blank=True)),
                ('jd_cleanse_user', models.TextField(blank=True)),
                ('cover_letter', models.TextField(blank=True)),
                ('cover_letter_system', models.TextField(blank=True)),
                ('cover_letter_user', models.TextField(blank=True)),
                ('interview_prep', models.TextField(blank=True)),
                ('interview_prep_system', models.TextField(blank=True)),
                ('interview_prep_user', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System prompt profile',
                'verbose_name_plural': 'System prompt profiles',
            },
        ),
        migrations.AlterField(
            model_name='atsjudgeprofile',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Null for system-wide admin-managed profiles. Legacy per-user rows are ignored at runtime.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ats_judge_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
