# Generated by Django 5.2.11 on 2026-08-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0029_appautomationsettings_export_replacements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appautomationsettings",
            name="pipeline_to_vetting_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
