# Generated by Django 5.2.11 on 2026-08-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0030_alter_appautomationsettings_pipeline_to_vetting_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="optimizerworkflow",
            name="step_llm_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Step-specific LLM config mapping step ids ('writer', 'jd_cleanse', etc.) to {'provider': '...', 'model': '...'}",
            ),
        ),
    ]
