# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0030_pipeline_resume_optimization"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpromptprofile",
            name="writer_system",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userpromptprofile",
            name="writer_user",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userpromptprofile",
            name="ats_judge_system",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userpromptprofile",
            name="ats_judge_user",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userpromptprofile",
            name="recruiter_judge_system",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userpromptprofile",
            name="recruiter_judge_user",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userpromptprofile",
            name="matching_system",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userpromptprofile",
            name="matching_user",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userpromptprofile",
            name="insights_system",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userpromptprofile",
            name="insights_user",
            field=models.TextField(blank=True),
        ),
    ]
