# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0031_userpromptprofile_system_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmproviderpreference",
            name="rate_limit_rpm",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional max requests per minute for this provider+model row. Empty = use env/provider defaults or no limit.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="llmproviderpreference",
            name="rate_limit_tpm",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional max input tokens per minute (estimated) for this row. Empty = use env/provider defaults or no limit.",
                null=True,
            ),
        ),
    ]
