# Generated by Django 5.2.11 on 2026-08-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0031_optimizerworkflow_step_llm_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='llm_tokens_per_day',
            field=models.PositiveIntegerField(default=0, help_text='Daily LLM token cap. 0 = unlimited or env default.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_display',
            field=models.CharField(blank=True, default='', help_text='Commercial price display (e.g. $0, $29/mo, $99/mo).', max_length=64),
        ),
    ]
