# Generated by Django 5.2.11 on 2026-08-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0032_plan_llm_tokens_per_day_plan_price_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='appautomationsettings',
            name='cleanup_job_retention_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='Cleanup Manager: remove non-applied jobs older than this many days (default 14 days / 2 weeks; 0 = off).'),
        ),
        migrations.AlterField(
            model_name='appautomationsettings',
            name='cleanup_applying_retention_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='Cleanup Manager: remove Applying-stage rows older than this many days (0 = off).'),
        ),
        migrations.AlterField(
            model_name='appautomationsettings',
            name='cleanup_pipeline_retention_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='Cleanup Manager: remove Pipeline-stage rows older than this many days (0 = off).'),
        ),
        migrations.AlterField(
            model_name='appautomationsettings',
            name='cleanup_vetting_retention_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='Cleanup Manager: remove Vetting-stage rows older than this many days (0 = off).'),
        ),
    ]
