# Generated by Django 5.2.11 on 2026-08-30 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0033_appautomationsettings_cleanup_job_retention_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMDailyUsageBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField(db_index=True)),
                ('query_kind', models.CharField(db_index=True, max_length=64)),
                ('provider', models.CharField(db_index=True, max_length=64)),
                ('model', models.CharField(db_index=True, help_text='Resolved model name, or __default__ when empty.', max_length=128)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('sum_input_tokens', models.BigIntegerField(default=0)),
                ('sum_output_tokens', models.BigIntegerField(default=0)),
                ('sum_cached_tokens', models.BigIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_daily_usage_breakdowns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM daily usage breakdown',
                'verbose_name_plural': 'LLM daily usage breakdowns',
                'indexes': [models.Index(fields=['owner', 'period_date'], name='resume_app__owner_i_665cba_idx')],
                'unique_together': {('owner', 'period_date', 'query_kind', 'provider', 'model')},
            },
        ),
    ]
