# Generated by Django 5.2.11 on 2026-09-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0036_remove_adzuna_from_stored_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsearchtaskrun',
            name='details',
            field=models.JSONField(blank=True, default=list, help_text='Itemized audit log of fetched jobs and their elimination/saved status for recent runs.'),
        ),
    ]
