# Generated by Django 5.2.11 on 2026-09-28 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0037_jobsearchtaskrun_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationattemptstep',
            name='attempt',
        ),
        migrations.AlterUniqueTogether(
            name='atsautosubmitstats',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='atsautosubmitstats',
            name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='sitecredential',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sitecredential',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='appautomationsettings',
            name='apply_agent_enabled',
        ),
        migrations.RemoveField(
            model_name='appautomationsettings',
            name='apply_agent_llm_model',
        ),
        migrations.RemoveField(
            model_name='appautomationsettings',
            name='apply_agent_llm_provider',
        ),
        migrations.RemoveField(
            model_name='appautomationsettings',
            name='apply_allowed_ats',
        ),
        migrations.RemoveField(
            model_name='appautomationsettings',
            name='apply_automation_mode',
        ),
        migrations.RemoveField(
            model_name='appautomationsettings',
            name='apply_browser_show_window',
        ),
        migrations.RemoveField(
            model_name='appautomationsettings',
            name='apply_full_auto_min_clean_submits',
        ),
        migrations.RemoveField(
            model_name='appautomationsettings',
            name='apply_generic_fallback_enabled',
        ),
        migrations.RemoveField(
            model_name='appautomationsettings',
            name='apply_min_optimizer_score',
        ),
        migrations.RemoveField(
            model_name='appautomationsettings',
            name='apply_resume_upload_format',
        ),
        migrations.DeleteModel(
            name='ApplicationAttempt',
        ),
        migrations.DeleteModel(
            name='ApplicationAttemptStep',
        ),
        migrations.DeleteModel(
            name='AtsAutoSubmitStats',
        ),
        migrations.DeleteModel(
            name='SiteCredential',
        ),
    ]
