# Generated by Django 5.2.11 on 2026-09-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0038_remove_applicationattemptstep_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appautomationsettings',
            name='weekly_target_applications',
            field=models.PositiveSmallIntegerField(default=10, help_text='Target applications to submit per week.'),
        ),
        migrations.AddField(
            model_name='pipelineentry',
            name='applied_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when moved to Done / applied.', null=True),
        ),
    ]
