# Generated by Django 5.2.11 on 2026-10-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0039_appautomationsettings_weekly_target_applications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appautomationsettings',
            name='cleanup_job_retention_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Cleanup Manager: remove non-applied jobs older than this many days (default 7 days / 1 week; 0 = off).'),
        ),
        migrations.AlterField(
            model_name='appautomationsettings',
            name='cleanup_pipeline_retention_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Cleanup Manager: remove Pipeline-stage rows older than this many days (default 7 days).'),
        ),
        migrations.AlterField(
            model_name='pipelineentry',
            name='stage',
            field=models.CharField(blank=True, choices=[('pipeline', 'Pipeline'), ('vetting', 'Vetting'), ('applying', 'Applying'), ('done', 'Done'), ('deleted', 'Deleted'), ('expired', 'Expired')], default='', help_text='Lightweight stage for this job in the pipeline (e.g. vetting, applying, done). Blank means legacy/default pipeline.', max_length=16),
        ),
    ]
