# Generated by Django 5.2.11 on 2026-10-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0040_alter_appautomationsettings_cleanup_job_retention_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systempromptprofile',
            name='skill_radar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='systempromptprofile',
            name='skill_radar_system',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='systempromptprofile',
            name='skill_radar_user',
            field=models.TextField(blank=True),
        ),
    ]
