# Generated by Django 5.2.11 on 2026-10-02 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0041_systempromptprofile_skill_radar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineentry',
            name='next_interview_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelineentry',
            name='post_apply_substatus',
            field=models.CharField(blank=True, choices=[('applied_pending', 'Applied (Awaiting Response)'), ('recruiter_call', 'Recruiter Screen / Call'), ('hiring_manager', 'Hiring Manager Screen'), ('panel_interview', 'Panel / Tech Deep Dive'), ('offer', 'Offer Received'), ('archived_rejected', 'Not Moving Forward'), ('withdrawn', 'Candidate Withdrawn')], db_index=True, default='applied_pending', help_text='Detailed stage/milestone after applying (e.g. Recruiter Call, Hiring Manager, Panel, Offer).', max_length=32),
        ),
        migrations.AddField(
            model_name='pipelineentry',
            name='post_apply_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmployerInterviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(choices=[('applied_pending', 'Applied (Awaiting Response)'), ('recruiter_call', 'Recruiter Screen / Call'), ('hiring_manager', 'Hiring Manager Screen'), ('panel_interview', 'Panel / Tech Deep Dive'), ('offer', 'Offer Received'), ('archived_rejected', 'Not Moving Forward'), ('withdrawn', 'Candidate Withdrawn')], default='recruiter_call', max_length=32)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=45, help_text='Estimated meeting duration in minutes.')),
                ('interviewer_names', models.CharField(blank=True, default='', help_text='Names/titles of interviewers or recruiters.', max_length=255)),
                ('location_or_link', models.CharField(blank=True, default='', help_text='Meeting URL or physical office campus location.', max_length=500)),
                ('notes', models.TextField(blank=True, default='', help_text='Preparation notes, discussion topics, or follow-up items.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_events', to=settings.AUTH_USER_MODEL)),
                ('pipeline_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_events', to='resume_app.pipelineentry')),
            ],
            options={
                'ordering': ['scheduled_at', '-created_at'],
            },
        ),
    ]
