# Generated by Django 5.2.11 on 2026-10-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0042_pipelineentry_next_interview_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appautomationsettings',
            name='pipeline_match_score_min',
            field=models.PositiveSmallIntegerField(default=70, help_text='Promote Pipeline → Vetting when Match Score (%) is >= this (0–100).'),
        ),
    ]
