# Generated by Django 5.2.11 on 2026-10-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0043_appautomationsettings_pipeline_match_score_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appautomationsettings',
            name='pipeline_match_score_min',
            field=models.PositiveSmallIntegerField(default=60, help_text='Promote Pipeline → Vetting when Match Score (%) is >= this (0–100).'),
        ),
    ]
