# Generated by Django 5.2.11 on 2026-10-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0044_alter_appautomationsettings_pipeline_match_score_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='appautomationsettings',
            name='pipeline_purge_match_score_max',
            field=models.PositiveSmallIntegerField(default=25, help_text='Cleanup Manager & Pipeline Manager: auto-dismiss New (Pipeline) jobs when Match Score (%) is strictly below this threshold (0-100; 0 to disable).'),
        ),
    ]
