# Generated by Django 5.2.11 on 2026-10-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0045_appautomationsettings_pipeline_purge_match_score_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineentry',
            name='vetting_core_competencies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pipelineentry',
            name='vetting_stretch_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
