# Generated by Django 5.2.11 on 2026-10-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0046_pipelineentry_vetting_core_competencies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineentry',
            name='vetting_core_competencies',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='pipelineentry',
            name='vetting_stretch_skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
