# Generated by Django 5.2.11 on 2026-10-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0047_alter_pipelineentry_vetting_core_competencies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineentry',
            name='vetting_match_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
