# Generated by Django 5.2.11 on 2026-10-06 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0048_pipelineentry_vetting_match_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineentry',
            name='applied_optimized_resume',
            field=models.ForeignKey(blank=True, help_text='Optimized resume snapshot used when marked applied.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_pipeline_entries', to='resume_app.optimizedresume'),
        ),
        migrations.AddField(
            model_name='pipelineentry',
            name='applied_resume_markdown',
            field=models.TextField(blank=True, default='', help_text='Markdown snapshot of the tailored/applied resume when moved to Applied.'),
        ),
    ]
