# Generated by Django 5.2.11 on 2026-10-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0049_pipelineentry_applied_optimized_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineentry',
            name='applied_resume_markdown',
            field=models.TextField(blank=True, default='', help_text='Markdown snapshot of the tailored/applied resume when moved to Applied.', null=True),
        ),
    ]
